version: '3'
services:
    # API Gateway
    nginx:
        image: complex-nginx
        restart: always
        ports:
            - "3050:80"
        depends_on: 
            - web
            - api        
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        build:            
            context: ./nginx
            dockerfile: Dockerfile.dev
    # Database (postgres)
    postgres:
        image: postgres:latest
        ports: 
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment: 
            - POSTGRES_PASSWORD=pass
    # Redis
    redis:
        image: redis:latest
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1s
            timeout: 3s
            retries: 30
    # App images
    web:
        stdin_open: true # required so that react doesn't exit right away
        image: 'complex-web'
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./client:/app        
    api:
        image: 'complex-server'
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGHOST=postgres
            - PGUSER=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=pass            
            - PGPORT=5432
        depends_on: 
            redis:
                condition: service_healthy
            postgres:
                condition: service_healthy
    worker:
        image: 'complex-worker'
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379           
        depends_on: 
            redis:
                condition: service_healthy
            postgres:
                condition: service_healthy