apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    # Allows this to be discoverable by the Label selector system.
    # Can be any keyword.
    component: web
spec:
  containers:    
      # Referenceable name for networking to other containers within the pod
      # or to get more information for the running container within the pod (e.g. logging)
    - name: client 
      image: stephengrider/multi-client
      ports:
        # Nginx port of the image exposed to the outside world
        - containerPort: 3000