FROM node:lts-alpine

WORKDIR /app

COPY ./package.json ./

RUN npm install

# Even with volumes, this is useful so that the container can run as a standalone
COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]